name: Deploy Infrastructure and Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'photo'
  AZURE_RESOURCE_GROUP: 'hf'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. A kód letöltése
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Bejelentkezés az Azure-ba a mesterkulccsal
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 3. INFRASTRUCTURE AS CODE (Bicep fájl futtatása)
    - name: Deploy Azure Infrastructure (IaC)
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./infra/main.bicep
        parameters: webAppName=${{ env.AZURE_WEBAPP_NAME }} databaseUrl='${{ secrets.DATABASE_URL }}'
        failOnStdErr: false

    # 4. Python környezet beállítása
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # 5. Függőségek telepítése
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 6. A tényleges Python alkalmazás telepítése az Azure-ra
    - name: Deploy Web App Code
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: .
